spring.application.name=order-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:orders}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:orders}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:8081/realms/ecommerce}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:8081/realms/ecommerce/protocol/openid-connect/certs}
external.customer-base-url=${CUSTOMER_BASE_URL:http://localhost:8089}
external.catalog-base-url=${CATALOG_BASE_URL:http://localhost:8089}
external.payment-base-url=${PAYMENT_BASE_URL:http://localhost:8089}
external.notification-base-url=${NOTIFICATION_BASE_URL:http://localhost:8089}
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.tracing.sampling.probability=1.0

# Redireciona os traces e métricas diretamente para o console do terminal
otel.traces.exporter=logging
otel.metrics.exporter=logging
otel.logs.exporter=logging

# Configura o nível de log do Spring/Otel para garantir que os traces apareçam
logging.level.io.opentelemetry=INFO
